version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/ssl:/etc/nginx/ssl:ro"
    depends_on:
      - backend
      - frontend
    networks:
      - industrace-network
    restart: unless-stopped
    labels:
      - "traefik.enable=false"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: industrace_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: industrace
    volumes:
      - industrace_postgres_data:/var/lib/postgresql/data
    networks:
      - industrace-network
    expose:
      - "5432"
    restart: unless-stopped

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://industrace_user:secure_password_123@db:5432/industrace
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=https://localhost,https://127.0.0.1,https://industrace.local
      - ENVIRONMENT=production
      - DEBUG=false
      - SECURE_COOKIES=true
      - SAME_SITE_COOKIES=strict
    depends_on:
      - db
    networks:
      - industrace-network
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - industrace-network
    expose:
      - "80"
    restart: unless-stopped

volumes:
  industrace_postgres_data:

networks:
  industrace-network:
    driver: bridge