"""enhance_role_model_with_inheritance

Revision ID: 9003ea70d4cb
Revises: c47d344c1250
Create Date: 2025-07-21 07:44:11.362036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9003ea70d4cb'
down_revision: Union[str, None] = 'c47d344c1250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('is_inheritable', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('parent_role_id', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'roles', 'roles', ['parent_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'parent_role_id')
    op.drop_column('roles', 'is_inheritable')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
